#! /bin/env sh

tmux select-window -t :5 || exit 1
cd build || exit 1

loops=50
for i in $(seq $loops)
do
  rm ../output/*
  echo ""
  echo "========================"
  timeout 5s ./rlr -c 4 --loops 1
  [ $? = 0 ] || break
done

if [ $i != $loops ]
then echo "managed to bork it"
else echo "okay you win"
fi

ls ../output
cat ../output/*
rm ../output/*

