#! /bin/env sh

verbose=no
test_file=

for arg do
  case arg in
    -v)        verbose=yes      ;;
    --verbose) verbose=yes      ;;
    *)         test_file="$arg" ;;
  esac
done

red="\033[0;31m"
green="\033[0;32m"
no_color="\033[0m"

tmp="$(mktemp "/tmp/stderr-of-test-os-hw2-date-$(date)-pid-$$-rand-XXXXX")"

printf "${green}Testing $test_file ...${no_color}"
chmod +x "$test_file"

if [ verbose = yes ]
then printf "\n"; "$test_file"
else "$test_file" > /dev/null 2> "$tmp"
fi

if [ $? != 0 ]
then printf "${red}Failed${no_color}\n" ; cat "$tmp"
else printf "${green}Passed${no_color}\n"
fi

rm "$tmp"

