#! /bin/env sh

test_one () {

  verbose=no
  command="echo 'test command not set properly' >&2; exit 1"

  for arg do
    case "$arg" in
      -v)        verbose=yes      ;;
      --verbose) verbose=yes      ;;
      '')                         ;;
      *)         command="$arg"   ;;
    esac
  done

  red="\033[0;31m"
  green="\033[0;32m"
  no_color="\033[0m"

  tmp="$(mktemp "/tmp/stderr-of-test-os-hw2-date-$(date)-pid-$$-rand-XXXXX")"

  if [ "$verbose" = yes ]
  then
    handle="========"
    printf "\n${green}${handle} Testing '$command' ${handle}${no_color}\n"
    sh -c "$command"
    if [ $? != 0 ]
    then printf   "${red}${handle}Test '${command}' failed${handle}${no_color}\n\n"
    else printf "${green}${handle}Test '${command}' passed${handle}${no_color}\n\n"
    fi
  else
    printf "${green}Testing '$command' ... ${no_color}"
    sh -c "$command" > /dev/null 2> "$tmp"
    if [ $? != 0 ]
    then printf "${red}Failed${no_color}\n" ; cat "$tmp"
    else printf "${green}Passed${no_color}\n"
    fi
  fi

  rm "$tmp"

}
