#!/bin/env sh

reality="$(
./rlr -c 732 --shm-i-want 'dont want' --shm-thank-you 'nope' --loops 4 --print   |
  sort)"

expectation="$(sort <<EOF
number of children: 732
'I want' shared memory name: 'dont want'
'thank you' shared memory name: 'nope'
loops per child: 4
EOF
)"

test "$expectation" = "$reality" && exit 0

tmp="$(mktemp -d /tmp/test-args-XXXXXXX)"
echo "$expectation" > "$tmp/e"
echo "$reality" > "$tmp/r"
diff "$tmp/e" "$tmp/r"
rm -rf "$tmp"

exit 1

