#ifndef DEFAULTS_H
#define DEFAULTS_H

#define DEFAULT_NUM_OF_CHILDREN 8
#define DEFAULT_OPERATIONS_PER_CHILD 1024
#define DEFAULT_OUTPUT_DIR "output"
#define DEFAULT_INPUT_FILE "data/1001-line-numbers.dat"
#define DEFAULT_SEGMENT_LENGTH 128;

#endif
